version: '3.2'
services:
  prometheus_centre:
    image: prom/prometheus:v2.9.0
    container_name: prometheus_centre
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - --web.enable-lifecycle
    volumes:
    - ./prometheus_centre.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - prometheus_1
    - prometheus_2
  prometheus_1:
    image: prom/prometheus:v2.9.0
    container_name: prometheus_1
    ports:
      - 9089:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./prometheus_1.yml:/etc/prometheus/prometheus.yml:ro
  prometheus_2:
    image: prom/prometheus:v2.9.0
    container_name: prometheus_2
    ports:
      - 9088:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./prometheus_2.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - cadvisor
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
